//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("conservadoraModel", "fk_balancetes_condominios1", "condominios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConservadoraSiteMVC2.Models.condominio), "atas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConservadoraSiteMVC2.Models.ata), true)]
[assembly: EdmRelationshipAttribute("conservadoraModel", "fk_balancetes_condominios10", "condominios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConservadoraSiteMVC2.Models.condominio), "balancetes", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConservadoraSiteMVC2.Models.balancete), true)]
[assembly: EdmRelationshipAttribute("conservadoraModel", "fk_Boletos_Moradores1", "moradores", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConservadoraSiteMVC2.Models.moradores), "boletos", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConservadoraSiteMVC2.Models.boleto), true)]
[assembly: EdmRelationshipAttribute("conservadoraModel", "fk_condominios_has_inquilinos_condominios1", "condominios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConservadoraSiteMVC2.Models.condominio), "condominios_moradores", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConservadoraSiteMVC2.Models.condominios_moradores), true)]
[assembly: EdmRelationshipAttribute("conservadoraModel", "fk_Recados_condominios1", "condominios", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConservadoraSiteMVC2.Models.condominio), "recados", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConservadoraSiteMVC2.Models.recado), true)]
[assembly: EdmRelationshipAttribute("conservadoraModel", "fk_condominios_has_inquilinos_inquilinos1", "moradores", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(ConservadoraSiteMVC2.Models.moradores), "condominios_moradores", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(ConservadoraSiteMVC2.Models.condominios_moradores), true)]

#endregion

namespace ConservadoraSiteMVC2.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class conservadoraEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new conservadoraEntities object using the connection string found in the 'conservadoraEntities' section of the application configuration file.
        /// </summary>
        public conservadoraEntities() : base("name=conservadoraEntities", "conservadoraEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new conservadoraEntities object.
        /// </summary>
        public conservadoraEntities(string connectionString) : base(connectionString, "conservadoraEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new conservadoraEntities object.
        /// </summary>
        public conservadoraEntities(EntityConnection connection) : base(connection, "conservadoraEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ata> atas
        {
            get
            {
                if ((_atas == null))
                {
                    _atas = base.CreateObjectSet<ata>("atas");
                }
                return _atas;
            }
        }
        private ObjectSet<ata> _atas;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<balancete> balancetes
        {
            get
            {
                if ((_balancetes == null))
                {
                    _balancetes = base.CreateObjectSet<balancete>("balancetes");
                }
                return _balancetes;
            }
        }
        private ObjectSet<balancete> _balancetes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<boleto> boletos
        {
            get
            {
                if ((_boletos == null))
                {
                    _boletos = base.CreateObjectSet<boleto>("boletos");
                }
                return _boletos;
            }
        }
        private ObjectSet<boleto> _boletos;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<condominio> condominios
        {
            get
            {
                if ((_condominios == null))
                {
                    _condominios = base.CreateObjectSet<condominio>("condominios");
                }
                return _condominios;
            }
        }
        private ObjectSet<condominio> _condominios;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<condominios_moradores> condominios_moradores
        {
            get
            {
                if ((_condominios_moradores == null))
                {
                    _condominios_moradores = base.CreateObjectSet<condominios_moradores>("condominios_moradores");
                }
                return _condominios_moradores;
            }
        }
        private ObjectSet<condominios_moradores> _condominios_moradores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<moradores> moradores
        {
            get
            {
                if ((_moradores == null))
                {
                    _moradores = base.CreateObjectSet<moradores>("moradores");
                }
                return _moradores;
            }
        }
        private ObjectSet<moradores> _moradores;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<recado> recados
        {
            get
            {
                if ((_recados == null))
                {
                    _recados = base.CreateObjectSet<recado>("recados");
                }
                return _recados;
            }
        }
        private ObjectSet<recado> _recados;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the atas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToatas(ata ata)
        {
            base.AddObject("atas", ata);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the balancetes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTobalancetes(balancete balancete)
        {
            base.AddObject("balancetes", balancete);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the boletos EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToboletos(boleto boleto)
        {
            base.AddObject("boletos", boleto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the condominios EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocondominios(condominio condominio)
        {
            base.AddObject("condominios", condominio);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the condominios_moradores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTocondominios_moradores(condominios_moradores condominios_moradores)
        {
            base.AddObject("condominios_moradores", condominios_moradores);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the moradores EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTomoradores(moradores moradores)
        {
            base.AddObject("moradores", moradores);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the recados EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorecados(recado recado)
        {
            base.AddObject("recados", recado);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="conservadoraModel", Name="ata")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ata : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ata object.
        /// </summary>
        /// <param name="idata">Initial value of the idata property.</param>
        /// <param name="idcondominios">Initial value of the idcondominios property.</param>
        public static ata Createata(global::System.Int32 idata, global::System.Int32 idcondominios)
        {
            ata ata = new ata();
            ata.idata = idata;
            ata.idcondominios = idcondominios;
            return ata;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String caminhoArquivo
        {
            get
            {
                return _caminhoArquivo;
            }
            set
            {
                OncaminhoArquivoChanging(value);
                ReportPropertyChanging("caminhoArquivo");
                _caminhoArquivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("caminhoArquivo");
                OncaminhoArquivoChanged();
            }
        }
        private global::System.String _caminhoArquivo;
        partial void OncaminhoArquivoChanging(global::System.String value);
        partial void OncaminhoArquivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private Nullable<global::System.DateTime> _data;
        partial void OndataChanging(Nullable<global::System.DateTime> value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idata
        {
            get
            {
                return _idata;
            }
            set
            {
                if (_idata != value)
                {
                    OnidataChanging(value);
                    ReportPropertyChanging("idata");
                    _idata = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idata");
                    OnidataChanged();
                }
            }
        }
        private global::System.Int32 _idata;
        partial void OnidataChanging(global::System.Int32 value);
        partial void OnidataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcondominios
        {
            get
            {
                return _idcondominios;
            }
            set
            {
                OnidcondominiosChanging(value);
                ReportPropertyChanging("idcondominios");
                _idcondominios = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idcondominios");
                OnidcondominiosChanged();
            }
        }
        private global::System.Int32 _idcondominios;
        partial void OnidcondominiosChanging(global::System.Int32 value);
        partial void OnidcondominiosChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_balancetes_condominios1", "condominios")]
        public condominio condominio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_balancetes_condominios1", "condominios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_balancetes_condominios1", "condominios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<condominio> condominioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_balancetes_condominios1", "condominios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<condominio>("conservadoraModel.fk_balancetes_condominios1", "condominios", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="conservadoraModel", Name="balancete")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class balancete : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new balancete object.
        /// </summary>
        /// <param name="idbalancete">Initial value of the idbalancete property.</param>
        /// <param name="idcondominios">Initial value of the idcondominios property.</param>
        public static balancete Createbalancete(global::System.Int32 idbalancete, global::System.Int32 idcondominios)
        {
            balancete balancete = new balancete();
            balancete.idbalancete = idbalancete;
            balancete.idcondominios = idcondominios;
            return balancete;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String caminhoArquivo
        {
            get
            {
                return _caminhoArquivo;
            }
            set
            {
                OncaminhoArquivoChanging(value);
                ReportPropertyChanging("caminhoArquivo");
                _caminhoArquivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("caminhoArquivo");
                OncaminhoArquivoChanged();
            }
        }
        private global::System.String _caminhoArquivo;
        partial void OncaminhoArquivoChanging(global::System.String value);
        partial void OncaminhoArquivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private Nullable<global::System.DateTime> _data;
        partial void OndataChanging(Nullable<global::System.DateTime> value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String descricao
        {
            get
            {
                return _descricao;
            }
            set
            {
                OndescricaoChanging(value);
                ReportPropertyChanging("descricao");
                _descricao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("descricao");
                OndescricaoChanged();
            }
        }
        private global::System.String _descricao;
        partial void OndescricaoChanging(global::System.String value);
        partial void OndescricaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idbalancete
        {
            get
            {
                return _idbalancete;
            }
            set
            {
                if (_idbalancete != value)
                {
                    OnidbalanceteChanging(value);
                    ReportPropertyChanging("idbalancete");
                    _idbalancete = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idbalancete");
                    OnidbalanceteChanged();
                }
            }
        }
        private global::System.Int32 _idbalancete;
        partial void OnidbalanceteChanging(global::System.Int32 value);
        partial void OnidbalanceteChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcondominios
        {
            get
            {
                return _idcondominios;
            }
            set
            {
                OnidcondominiosChanging(value);
                ReportPropertyChanging("idcondominios");
                _idcondominios = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idcondominios");
                OnidcondominiosChanged();
            }
        }
        private global::System.Int32 _idcondominios;
        partial void OnidcondominiosChanging(global::System.Int32 value);
        partial void OnidcondominiosChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_balancetes_condominios10", "condominios")]
        public condominio condominio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_balancetes_condominios10", "condominios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_balancetes_condominios10", "condominios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<condominio> condominioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_balancetes_condominios10", "condominios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<condominio>("conservadoraModel.fk_balancetes_condominios10", "condominios", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="conservadoraModel", Name="boleto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class boleto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new boleto object.
        /// </summary>
        /// <param name="idboletos">Initial value of the idboletos property.</param>
        /// <param name="idmoradores">Initial value of the idmoradores property.</param>
        public static boleto Createboleto(global::System.Int32 idboletos, global::System.Int32 idmoradores)
        {
            boleto boleto = new boleto();
            boleto.idboletos = idboletos;
            boleto.idmoradores = idmoradores;
            return boleto;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String caminhoArquivo
        {
            get
            {
                return _caminhoArquivo;
            }
            set
            {
                OncaminhoArquivoChanging(value);
                ReportPropertyChanging("caminhoArquivo");
                _caminhoArquivo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("caminhoArquivo");
                OncaminhoArquivoChanged();
            }
        }
        private global::System.String _caminhoArquivo;
        partial void OncaminhoArquivoChanging(global::System.String value);
        partial void OncaminhoArquivoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data
        {
            get
            {
                return _data;
            }
            set
            {
                OndataChanging(value);
                ReportPropertyChanging("data");
                _data = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data");
                OndataChanged();
            }
        }
        private Nullable<global::System.DateTime> _data;
        partial void OndataChanging(Nullable<global::System.DateTime> value);
        partial void OndataChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idboletos
        {
            get
            {
                return _idboletos;
            }
            set
            {
                if (_idboletos != value)
                {
                    OnidboletosChanging(value);
                    ReportPropertyChanging("idboletos");
                    _idboletos = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idboletos");
                    OnidboletosChanged();
                }
            }
        }
        private global::System.Int32 _idboletos;
        partial void OnidboletosChanging(global::System.Int32 value);
        partial void OnidboletosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idmoradores
        {
            get
            {
                return _idmoradores;
            }
            set
            {
                OnidmoradoresChanging(value);
                ReportPropertyChanging("idmoradores");
                _idmoradores = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idmoradores");
                OnidmoradoresChanged();
            }
        }
        private global::System.Int32 _idmoradores;
        partial void OnidmoradoresChanging(global::System.Int32 value);
        partial void OnidmoradoresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String sitiuacao
        {
            get
            {
                return _sitiuacao;
            }
            set
            {
                OnsitiuacaoChanging(value);
                ReportPropertyChanging("sitiuacao");
                _sitiuacao = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("sitiuacao");
                OnsitiuacaoChanged();
            }
        }
        private global::System.String _sitiuacao;
        partial void OnsitiuacaoChanging(global::System.String value);
        partial void OnsitiuacaoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Single> valor
        {
            get
            {
                return _valor;
            }
            set
            {
                OnvalorChanging(value);
                ReportPropertyChanging("valor");
                _valor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("valor");
                OnvalorChanged();
            }
        }
        private Nullable<global::System.Single> _valor;
        partial void OnvalorChanging(Nullable<global::System.Single> value);
        partial void OnvalorChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_Boletos_Moradores1", "moradores")]
        public moradores moradore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<moradores>("conservadoraModel.fk_Boletos_Moradores1", "moradores").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<moradores>("conservadoraModel.fk_Boletos_Moradores1", "moradores").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<moradores> moradoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<moradores>("conservadoraModel.fk_Boletos_Moradores1", "moradores");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<moradores>("conservadoraModel.fk_Boletos_Moradores1", "moradores", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="conservadoraModel", Name="condominio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class condominio : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new condominio object.
        /// </summary>
        /// <param name="idcondominios">Initial value of the idcondominios property.</param>
        public static condominio Createcondominio(global::System.Int32 idcondominios)
        {
            condominio condominio = new condominio();
            condominio.idcondominios = idcondominios;
            return condominio;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String endereco
        {
            get
            {
                return _endereco;
            }
            set
            {
                OnenderecoChanging(value);
                ReportPropertyChanging("endereco");
                _endereco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("endereco");
                OnenderecoChanged();
            }
        }
        private global::System.String _endereco;
        partial void OnenderecoChanging(global::System.String value);
        partial void OnenderecoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcondominios
        {
            get
            {
                return _idcondominios;
            }
            set
            {
                if (_idcondominios != value)
                {
                    OnidcondominiosChanging(value);
                    ReportPropertyChanging("idcondominios");
                    _idcondominios = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcondominios");
                    OnidcondominiosChanged();
                }
            }
        }
        private global::System.Int32 _idcondominios;
        partial void OnidcondominiosChanging(global::System.Int32 value);
        partial void OnidcondominiosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sindico
        {
            get
            {
                return _Sindico;
            }
            set
            {
                OnSindicoChanging(value);
                ReportPropertyChanging("Sindico");
                _Sindico = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sindico");
                OnSindicoChanged();
            }
        }
        private Nullable<global::System.Int32> _Sindico;
        partial void OnSindicoChanging(Nullable<global::System.Int32> value);
        partial void OnSindicoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_balancetes_condominios1", "atas")]
        public EntityCollection<ata> atas
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ata>("conservadoraModel.fk_balancetes_condominios1", "atas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ata>("conservadoraModel.fk_balancetes_condominios1", "atas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_balancetes_condominios10", "balancetes")]
        public EntityCollection<balancete> balancetes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<balancete>("conservadoraModel.fk_balancetes_condominios10", "balancetes");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<balancete>("conservadoraModel.fk_balancetes_condominios10", "balancetes", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_condominios_has_inquilinos_condominios1", "condominios_moradores")]
        public EntityCollection<condominios_moradores> condominios_moradores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<condominios_moradores>("conservadoraModel.fk_condominios_has_inquilinos_condominios1", "condominios_moradores");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<condominios_moradores>("conservadoraModel.fk_condominios_has_inquilinos_condominios1", "condominios_moradores", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_Recados_condominios1", "recados")]
        public EntityCollection<recado> recados
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<recado>("conservadoraModel.fk_Recados_condominios1", "recados");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<recado>("conservadoraModel.fk_Recados_condominios1", "recados", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="conservadoraModel", Name="condominios_moradores")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class condominios_moradores : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new condominios_moradores object.
        /// </summary>
        /// <param name="idcondominios">Initial value of the idcondominios property.</param>
        /// <param name="idmoradores">Initial value of the idmoradores property.</param>
        public static condominios_moradores Createcondominios_moradores(global::System.Int32 idcondominios, global::System.Int32 idmoradores)
        {
            condominios_moradores condominios_moradores = new condominios_moradores();
            condominios_moradores.idcondominios = idcondominios;
            condominios_moradores.idmoradores = idmoradores;
            return condominios_moradores;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcondominios
        {
            get
            {
                return _idcondominios;
            }
            set
            {
                if (_idcondominios != value)
                {
                    OnidcondominiosChanging(value);
                    ReportPropertyChanging("idcondominios");
                    _idcondominios = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idcondominios");
                    OnidcondominiosChanged();
                }
            }
        }
        private global::System.Int32 _idcondominios;
        partial void OnidcondominiosChanging(global::System.Int32 value);
        partial void OnidcondominiosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idmoradores
        {
            get
            {
                return _idmoradores;
            }
            set
            {
                if (_idmoradores != value)
                {
                    OnidmoradoresChanging(value);
                    ReportPropertyChanging("idmoradores");
                    _idmoradores = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idmoradores");
                    OnidmoradoresChanged();
                }
            }
        }
        private global::System.Int32 _idmoradores;
        partial void OnidmoradoresChanging(global::System.Int32 value);
        partial void OnidmoradoresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> isSindico
        {
            get
            {
                return _isSindico;
            }
            set
            {
                OnisSindicoChanging(value);
                ReportPropertyChanging("isSindico");
                _isSindico = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("isSindico");
                OnisSindicoChanged();
            }
        }
        private Nullable<global::System.Boolean> _isSindico;
        partial void OnisSindicoChanging(Nullable<global::System.Boolean> value);
        partial void OnisSindicoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_condominios_has_inquilinos_condominios1", "condominios")]
        public condominio condominio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_condominios_has_inquilinos_condominios1", "condominios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_condominios_has_inquilinos_condominios1", "condominios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<condominio> condominioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_condominios_has_inquilinos_condominios1", "condominios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<condominio>("conservadoraModel.fk_condominios_has_inquilinos_condominios1", "condominios", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_condominios_has_inquilinos_inquilinos1", "moradores")]
        public moradores moradore
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<moradores>("conservadoraModel.fk_condominios_has_inquilinos_inquilinos1", "moradores").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<moradores>("conservadoraModel.fk_condominios_has_inquilinos_inquilinos1", "moradores").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<moradores> moradoreReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<moradores>("conservadoraModel.fk_condominios_has_inquilinos_inquilinos1", "moradores");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<moradores>("conservadoraModel.fk_condominios_has_inquilinos_inquilinos1", "moradores", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="conservadoraModel", Name="moradores")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class moradores : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new moradores object.
        /// </summary>
        /// <param name="idmoradores">Initial value of the idmoradores property.</param>
        public static moradores Createmoradores(global::System.Int32 idmoradores)
        {
            moradores moradores = new moradores();
            moradores.idmoradores = idmoradores;
            return moradores;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String bloco
        {
            get
            {
                return _bloco;
            }
            set
            {
                OnblocoChanging(value);
                ReportPropertyChanging("bloco");
                _bloco = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("bloco");
                OnblocoChanged();
            }
        }
        private global::System.String _bloco;
        partial void OnblocoChanging(global::System.String value);
        partial void OnblocoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String cpf
        {
            get
            {
                return _cpf;
            }
            set
            {
                OncpfChanging(value);
                ReportPropertyChanging("cpf");
                _cpf = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("cpf");
                OncpfChanged();
            }
        }
        private global::System.String _cpf;
        partial void OncpfChanging(global::System.String value);
        partial void OncpfChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idmoradores
        {
            get
            {
                return _idmoradores;
            }
            set
            {
                if (_idmoradores != value)
                {
                    OnidmoradoresChanging(value);
                    ReportPropertyChanging("idmoradores");
                    _idmoradores = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idmoradores");
                    OnidmoradoresChanged();
                }
            }
        }
        private global::System.Int32 _idmoradores;
        partial void OnidmoradoresChanging(global::System.Int32 value);
        partial void OnidmoradoresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nome
        {
            get
            {
                return _nome;
            }
            set
            {
                OnnomeChanging(value);
                ReportPropertyChanging("nome");
                _nome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nome");
                OnnomeChanged();
            }
        }
        private global::System.String _nome;
        partial void OnnomeChanging(global::System.String value);
        partial void OnnomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String numero
        {
            get
            {
                return _numero;
            }
            set
            {
                OnnumeroChanging(value);
                ReportPropertyChanging("numero");
                _numero = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("numero");
                OnnumeroChanged();
            }
        }
        private global::System.String _numero;
        partial void OnnumeroChanging(global::System.String value);
        partial void OnnumeroChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_Boletos_Moradores1", "boletos")]
        public EntityCollection<boleto> boletos
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<boleto>("conservadoraModel.fk_Boletos_Moradores1", "boletos");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<boleto>("conservadoraModel.fk_Boletos_Moradores1", "boletos", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_condominios_has_inquilinos_inquilinos1", "condominios_moradores")]
        public EntityCollection<condominios_moradores> condominios_moradores
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<condominios_moradores>("conservadoraModel.fk_condominios_has_inquilinos_inquilinos1", "condominios_moradores");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<condominios_moradores>("conservadoraModel.fk_condominios_has_inquilinos_inquilinos1", "condominios_moradores", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="conservadoraModel", Name="recado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class recado : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new recado object.
        /// </summary>
        /// <param name="idcondominios">Initial value of the idcondominios property.</param>
        /// <param name="idrecados">Initial value of the idrecados property.</param>
        public static recado Createrecado(global::System.Int32 idcondominios, global::System.Int32 idrecados)
        {
            recado recado = new recado();
            recado.idcondominios = idcondominios;
            recado.idrecados = idrecados;
            return recado;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idcondominios
        {
            get
            {
                return _idcondominios;
            }
            set
            {
                OnidcondominiosChanging(value);
                ReportPropertyChanging("idcondominios");
                _idcondominios = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("idcondominios");
                OnidcondominiosChanged();
            }
        }
        private global::System.Int32 _idcondominios;
        partial void OnidcondominiosChanging(global::System.Int32 value);
        partial void OnidcondominiosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 idrecados
        {
            get
            {
                return _idrecados;
            }
            set
            {
                if (_idrecados != value)
                {
                    OnidrecadosChanging(value);
                    ReportPropertyChanging("idrecados");
                    _idrecados = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("idrecados");
                    OnidrecadosChanged();
                }
            }
        }
        private global::System.Int32 _idrecados;
        partial void OnidrecadosChanging(global::System.Int32 value);
        partial void OnidrecadosChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Texto
        {
            get
            {
                return _Texto;
            }
            set
            {
                OnTextoChanging(value);
                ReportPropertyChanging("Texto");
                _Texto = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Texto");
                OnTextoChanged();
            }
        }
        private global::System.String _Texto;
        partial void OnTextoChanging(global::System.String value);
        partial void OnTextoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Título
        {
            get
            {
                return _Título;
            }
            set
            {
                OnTítuloChanging(value);
                ReportPropertyChanging("Título");
                _Título = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Título");
                OnTítuloChanged();
            }
        }
        private global::System.String _Título;
        partial void OnTítuloChanging(global::System.String value);
        partial void OnTítuloChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("conservadoraModel", "fk_Recados_condominios1", "condominios")]
        public condominio condominio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_Recados_condominios1", "condominios").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_Recados_condominios1", "condominios").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<condominio> condominioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<condominio>("conservadoraModel.fk_Recados_condominios1", "condominios");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<condominio>("conservadoraModel.fk_Recados_condominios1", "condominios", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
