//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaConservadora.BalancetesWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BalancetesWeb.BalancetesWebSoap")]
    public interface BalancetesWebSoap {
        
        // CODEGEN: Parameter 'dadosDoArquivo' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalvaArquivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SistemaConservadora.BalancetesWeb.SalvaArquivoResponse SalvaArquivo(SistemaConservadora.BalancetesWeb.SalvaArquivoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/teste", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        SistemaConservadora.BalancetesWeb.moradores teste();
        
        // CODEGEN: Parameter 'DownloadBytesResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DownloadBytes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        SistemaConservadora.BalancetesWeb.DownloadBytesResponse DownloadBytes(SistemaConservadora.BalancetesWeb.DownloadBytesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/existeArquivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool existeArquivo(string nomeArquivo, string acesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornaLista", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        balancete[] RetornaLista(string acesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RetornaItem", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        SistemaConservadora.BalancetesWeb.balancete RetornaItem(int id, string acesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SalvaBalancete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool SalvaBalancete(SistemaConservadora.BalancetesWeb.balancete balancetesp, string acesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AdicionaBalancete", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool AdicionaBalancete(SistemaConservadora.BalancetesWeb.balancete balancetesp, string acesso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Apagar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RelatedEnd))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(StructuralObject))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(EntityKeyMember[]))]
        bool Apagar(int id, string acesso);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalvaArquivo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SalvaArquivoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] dadosDoArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string nomeArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string acesso;
        
        public SalvaArquivoRequest() {
        }
        
        public SalvaArquivoRequest(byte[] dadosDoArquivo, string nomeArquivo, string acesso) {
            this.dadosDoArquivo = dadosDoArquivo;
            this.nomeArquivo = nomeArquivo;
            this.acesso = acesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SalvaArquivoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SalvaArquivoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string SalvaArquivoResult;
        
        public SalvaArquivoResponse() {
        }
        
        public SalvaArquivoResponse(string SalvaArquivoResult) {
            this.SalvaArquivoResult = SalvaArquivoResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class moradores : EntityObject {
        
        private string blocoField;
        
        private string cpfField;
        
        private int idmoradoresField;
        
        private string loginField;
        
        private string nomeField;
        
        private string numeroField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string bloco {
            get {
                return this.blocoField;
            }
            set {
                this.blocoField = value;
                this.RaisePropertyChanged("bloco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string cpf {
            get {
                return this.cpfField;
            }
            set {
                this.cpfField = value;
                this.RaisePropertyChanged("cpf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int idmoradores {
            get {
                return this.idmoradoresField;
            }
            set {
                this.idmoradoresField = value;
                this.RaisePropertyChanged("idmoradores");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
                this.RaisePropertyChanged("login");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("senha");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(moradores))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(balancete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
                this.RaisePropertyChanged("EntitySetName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
                this.RaisePropertyChanged("EntityContainerName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
                this.RaisePropertyChanged("EntityKeyValues");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("Key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfcondominio))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfcondominio))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
                this.RaisePropertyChanged("EntityKey");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfcondominio : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(moradores))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(balancete))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class balancete : EntityObject {
        
        private string caminhoArquivoField;
        
        private System.Nullable<System.DateTime> dataField;
        
        private int idbalanceteField;
        
        private int idcondominiosField;
        
        private EntityReferenceOfcondominio condominioReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string caminhoArquivo {
            get {
                return this.caminhoArquivoField;
            }
            set {
                this.caminhoArquivoField = value;
                this.RaisePropertyChanged("caminhoArquivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int idbalancete {
            get {
                return this.idbalanceteField;
            }
            set {
                this.idbalanceteField = value;
                this.RaisePropertyChanged("idbalancete");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int idcondominios {
            get {
                return this.idcondominiosField;
            }
            set {
                this.idcondominiosField = value;
                this.RaisePropertyChanged("idcondominios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public EntityReferenceOfcondominio condominioReference {
            get {
                return this.condominioReferenceField;
            }
            set {
                this.condominioReferenceField = value;
                this.RaisePropertyChanged("condominioReference");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadBytes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadBytesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string nomeArquivo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string acesso;
        
        public DownloadBytesRequest() {
        }
        
        public DownloadBytesRequest(string nomeArquivo, string acesso) {
            this.nomeArquivo = nomeArquivo;
            this.acesso = acesso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DownloadBytesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DownloadBytesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DownloadBytesResult;
        
        public DownloadBytesResponse() {
        }
        
        public DownloadBytesResponse(byte[] DownloadBytesResult) {
            this.DownloadBytesResult = DownloadBytesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BalancetesWebSoapChannel : SistemaConservadora.BalancetesWeb.BalancetesWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BalancetesWebSoapClient : System.ServiceModel.ClientBase<SistemaConservadora.BalancetesWeb.BalancetesWebSoap>, SistemaConservadora.BalancetesWeb.BalancetesWebSoap {
        
        public BalancetesWebSoapClient() {
        }
        
        public BalancetesWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BalancetesWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BalancetesWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BalancetesWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaConservadora.BalancetesWeb.SalvaArquivoResponse SistemaConservadora.BalancetesWeb.BalancetesWebSoap.SalvaArquivo(SistemaConservadora.BalancetesWeb.SalvaArquivoRequest request) {
            return base.Channel.SalvaArquivo(request);
        }
        
        public string SalvaArquivo(byte[] dadosDoArquivo, string nomeArquivo, string acesso) {
            SistemaConservadora.BalancetesWeb.SalvaArquivoRequest inValue = new SistemaConservadora.BalancetesWeb.SalvaArquivoRequest();
            inValue.dadosDoArquivo = dadosDoArquivo;
            inValue.nomeArquivo = nomeArquivo;
            inValue.acesso = acesso;
            SistemaConservadora.BalancetesWeb.SalvaArquivoResponse retVal = ((SistemaConservadora.BalancetesWeb.BalancetesWebSoap)(this)).SalvaArquivo(inValue);
            return retVal.SalvaArquivoResult;
        }
        
        public SistemaConservadora.BalancetesWeb.moradores teste() {
            return base.Channel.teste();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SistemaConservadora.BalancetesWeb.DownloadBytesResponse SistemaConservadora.BalancetesWeb.BalancetesWebSoap.DownloadBytes(SistemaConservadora.BalancetesWeb.DownloadBytesRequest request) {
            return base.Channel.DownloadBytes(request);
        }
        
        public byte[] DownloadBytes(string nomeArquivo, string acesso) {
            SistemaConservadora.BalancetesWeb.DownloadBytesRequest inValue = new SistemaConservadora.BalancetesWeb.DownloadBytesRequest();
            inValue.nomeArquivo = nomeArquivo;
            inValue.acesso = acesso;
            SistemaConservadora.BalancetesWeb.DownloadBytesResponse retVal = ((SistemaConservadora.BalancetesWeb.BalancetesWebSoap)(this)).DownloadBytes(inValue);
            return retVal.DownloadBytesResult;
        }
        
        public bool existeArquivo(string nomeArquivo, string acesso) {
            return base.Channel.existeArquivo(nomeArquivo, acesso);
        }
        
        public balancete[] RetornaLista(string acesso) {
            return base.Channel.RetornaLista(acesso);
        }
        
        public SistemaConservadora.BalancetesWeb.balancete RetornaItem(int id, string acesso) {
            return base.Channel.RetornaItem(id, acesso);
        }
        
        public bool SalvaBalancete(SistemaConservadora.BalancetesWeb.balancete balancetesp, string acesso) {
            return base.Channel.SalvaBalancete(balancetesp, acesso);
        }
        
        public bool AdicionaBalancete(SistemaConservadora.BalancetesWeb.balancete balancetesp, string acesso) {
            return base.Channel.AdicionaBalancete(balancetesp, acesso);
        }
        
        public bool Apagar(int id, string acesso) {
            return base.Channel.Apagar(id, acesso);
        }
    }
}
